// src/components/react/Counter.tsx
/** @jsxImportSource react */
import { useState } from "react";

export function Counter() {
  const [count, setCount] = useState(0);
  return (
    <button
      className="rounded border bg-gray-200 p-3 hover:bg-gray-300"
      type="button"
      onClick={() => {
        setCount((count) => count + 1);
      }}
    >
      {count}
    </button>
  );
}

// src/components/solid/Counter.tsx
/** @jsxImportSource solid-js */

import {createSignal} from "solid-js";

export function Counter() {
    const [count, setCount] = createSignal(0);
    return (
        <button class="p-3 rounded bg-gray-200 border hover:bg-gray-300" type="button"
                onClick={() => setCount(count => count + 1)}>{count()}</button>
    );
}
